spring:

  data:
    mongodb:
      username: ${PROD_MONGO_USER}
      password: ${PROD_MONGO_PASSWORD}
      host: ${PROD_MONGO_HOST}
      port: ${PROD_MONGO_PORT}
      database: ${PROD_MONGO_DB}

  artemis:
    broker-url: ${PROD_ARTEMIS_BROKER_URL}
    user: ${PROD_ARTEMIS_USER}
    password: ${PROD_ARTEMIS_PASSWORD}

logging:
  level:
    com.alirizakaygusuz.gymcrm.workload_service: WARN