spring:
  artemis:
    broker-url: ${STG_ARTEMIS_BROKER_URL}
    user: ${STG_ARTEMIS_USER}
    password: ${STG_ARTEMIS_PASSWORD}

logging:
  level:
    com.alirizakaygusuz.gymcrm.workload_service: INFO