spring:
  artemis:
    broker-url: ${LOCAL_ARTEMIS_BROKER_URL}
    user: ${LOCAL_ARTEMIS_USER}
    password: ${LOCAL_ARTEMIS_PASSWORD}

logging:
  level:
    com.alirizakaygusuz.gymcrm.workload_service: DEBUG