spring:
  application:
    name: workload-service
  config:
    import: optional:file:workload-service/.env[.properties]

  mongodb:
    username: ${MONGO_USER}
    password: ${MONGO_PASSWORD}
    host: ${MONGO_HOST}
    port: ${MONGO_PORT}
    database: ${MONGO_DB}
    authentication-database: admin
    auto-index-creation: true

  artemis:
    broker-url: ${ARTEMIS_BROKER_URL}
    user: ${ARTEMIS_USER}
    password: ${ARTEMIS_PASSWORD}
  jms:
    pub-sub-domain: false
messaging:
  queues:
    workload: workload.queue

logging:
  level:
    com.alirizakaygusuz.gymcrm.workload_service: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET}

server:
  port: ${WORKLOAD_SERVICE_PORT}

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState
          show-details: always
        liveness:
          include: livenessState
          show-details: always
    info:
      enabled: true



info:
  app:
    name: Workload Service
    description: Trainer workload microservice developed by Ali Riza Kaygusuz
    version: 1.0-SNAPSHOT
  contact:
    name: Ali Riza Kaygusuz
