spring:
  datasource:
    url: jdbc:postgresql://${LOCAL_DB_HOST}:${LOCAL_DB_PORT}/${LOCAL_DB_NAME}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}

logging:
  level:
    com.alirizakaygusuz.gymcrm: DEBUG