spring:
  datasource:
    url: jdbc:postgresql://${DOCKER_DB_HOST}:${DOCKER_DB_PORT}/${DOCKER_DB_NAME}
    username: ${DOCKER_DB_USER}
    password: ${DOCKER_DB_PASSWORD}
  data:
    redis:
      host: ${DOCKER_REDIS_HOST}
      port: ${DOCKER_REDIS_PORT}
      password: ${DOCKER_REDIS_PASSWORD:}

  artemis:
    broker-url: ${DOCKER_ARTEMIS_BROKER_URL}
    user: ${DOCKER_ARTEMIS_USER}
    password: ${DOCKER_ARTEMIS_PASSWORD}

logging:
  level:
    com.alirizakaygusuz.gymcrm: INFO
