services:
  postgres:
    image: postgres:17.7
    container_name: ali-gymcrm-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ali-gymcrm_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    image: eclipse-temurin:17-jre
    container_name: ali-gymcrm-app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DOCKER_DB_HOST: ${DOCKER_DB_HOST}
      DOCKER_DB_PORT: ${DOCKER_DB_PORT}
      DOCKER_DB_NAME: ${DOCKER_DB_NAME}
      DOCKER_DB_USER: ${DOCKER_DB_USER}
      DOCKER_DB_PASSWORD: ${DOCKER_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "8080:8080"
    volumes:
      - ./target/gymcrm.jar:/app/gymcrm.jar
    command: java -jar /app/gymcrm.jar

volumes:
  ali-gymcrm_pgdata: