spring:
  config:
    import: optional:file:.env[.properties]
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms


security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  rate-limit:
    login:
      max-attempts: ${LOGIN_RATE_MAX_ATTEMPTS}
      block-duration: ${LOGIN_RATE_BLOCK_DURATION}
      redis-key-prefix: ${LOGIN_RATE_REDIS_KEY_PREFIX}

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      default:
        exclude: db ,jwtServiceHealth, trainingTypesHealth
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, db, jwtServiceHealth, trainingTypesHealth
          show-details: always
        liveness:
          include: livenessState
          show-details: always
    info:
      enabled: true


info:
  app:
    name: Gym CRM System
    description: Spring Boot Gym CRM project developed by Ali Riza Kaygusuz
    version: 1.0-SNAPSHOT
  build:
    artifact: gymcrm
    group: com.alirizakaygusuz.gymcrm
  contact:
    name: Ali Riza Kaygusuz