
# Application Properties
storage.init.enabled=true

storage.seed.trainees=classpath:seed/trainees.json
storage.seed.trainers=classpath:seed/trainers.json
storage.seed.trainings=classpath:seed/trainings.json