
spring.profiles.active=dev

db.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
db.username=${POSTGRES_USER}
db.password=${POSTGRES_PASSWORD}



hibernate.hbm2ddl.auto=validate
hibernate.show_sql=true
hibernate.format_sql=true