spring:
  config:
    import: optional:file:.env[.properties]
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}