services:
  postgres:
    image: postgres:17.7
    container_name: ali-gymcrm-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ali-gymcrm_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - gymcrm-network

  redis:
    image: redis:7-alpine
    container_name: ali-gymcrm-redis
    env_file:
      - .env
    ports:
      - "${DOCKER_REDIS_PORT}:6379"
    command: [ "redis-server", "--appendonly", "yes", "--appendfsync", "everysec" ]
    volumes:
      - ali-gymcrm_redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - gymcrm-network

  artemis:
    image: apache/activemq-artemis:latest
    container_name: ali-gymcrm-artemis
    env_file:
      - .env
    ports:
      - "${DOCKER_ARTEMIS_PORT}:61616"
      - "${DOCKER_ARTEMIS_CONSOLE_PORT}:8161"
    volumes:
      - ali-gymcrm_artemis:/var/lib/artemis/data
    environment:
      ARTEMIS_USER: ${DOCKER_ARTEMIS_USER}
      ARTEMIS_PASSWORD: ${DOCKER_ARTEMIS_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8161 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - gymcrm-network

  app:
    image: eclipse-temurin:17-jre
    container_name: ali-gymcrm-app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      artemis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker

      DOCKER_DB_HOST: ${DOCKER_DB_HOST}
      DOCKER_DB_PORT: ${DOCKER_DB_PORT}
      DOCKER_DB_NAME: ${DOCKER_DB_NAME}
      DOCKER_DB_USER: ${DOCKER_DB_USER}
      DOCKER_DB_PASSWORD: ${DOCKER_DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

      REDIS_HOST: ${DOCKER_REDIS_HOST}
      REDIS_PORT: ${DOCKER_REDIS_PORT}
      REDIS_PASSWORD: ${DOCKER_REDIS_PASSWORD}

      ARTEMIS_BROKER_URL: ${DOCKER_ARTEMIS_BROKER_URL}
      ARTEMIS_USER: ${DOCKER_ARTEMIS_USER}
      ARTEMIS_PASSWORD: ${DOCKER_ARTEMIS_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./target/gymcrm.jar:/app/gymcrm.jar
    command: [ "java", "-jar", "/app/gymcrm.jar" ]
    networks:
      - gymcrm-network

networks:
  gymcrm-network:
    driver: bridge
    name: gymcrm-network


volumes:
  ali-gymcrm_pgdata:
  ali-gymcrm_redis:
  ali-gymcrm_artemis: